name: Go

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.17', '1.18', '>=1.18']
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - run: docker-compose build
    - run: docker-compose up -d
    - run: go test -v main_test.go

  build:
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.17', '1.18', '>=1.18']
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - run: go build -v main.go
